[build]
  command = "npm run build && npm run functions"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200